version: '2'
services:
  twentyonepoints-app:
    image: twentyonepoints
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://twentyonepoints-postgresql:5432/TwentyOnePoints
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  twentyonepoints-postgresql:
    extends:
      file: postgresql.yml
      service: twentyonepoints-postgresql
